### PR TITLE
Use bubbles based spinner for all loading texts

### PR DESCRIPTION
**Pull request by athoscouto**
It should:
- Give a better look to the CLI commands
- Solve once and for all #104 

https://user-images.githubusercontent.com/7853668/233458814-3a791f57-eeda-46d2-83e5-0887a470ed8a.mov

### CODE REVIEW

**Comment by haaawk** [comment]
Why?

**Comment by athoscouto** [comment]
By the way, the issue described in #104 still happens to me with the loading bar every once in a while

**Comment by CodingDoug** [comment]
> By the way, the issue described in #104 still happens to me with the loading bar every once in a while

It happened to me last night as well during a live demo.

**Comment by glommer** [comment]
looks great, Athos!

**Review by glommer — APPROVED** [review]

**Pull request merged**
