### PR TITLE
auto update CLI

### LINKED ISSUE #266: [RFE] self updating cli
As a user I'd like to be able to update the cli client using a command like `turso update`

This is a very common feature for such tools

### PR DESCRIPTION
**Pull request by glommer**
Fixes #266

### CODE REVIEW

**Comment by glommer** [comment]
Note: I didn't test this on homebrew since we need to release a version with this on homebrew for the test to be accurate.
(I did test variations of this with copying the binary around, etc)

**Comment by glommer** [comment]
I did =(

**Review by haaawk — APPROVED** [review]
LGTM but it seems that some checks are failing

**Comment by glommer** [comment]
I updated it. But now it is failing with something I have no idea why =(

**Comment by glommer** [comment]
it was failing on a test.. maybe it re-run by itself?

**Comment by haaawk** [comment]
I rerun them. I fixed the tests today. Shouldn't be flaky any more.

**Pull request merged**
