### PR TITLE
experimental: local development server

### PR DESCRIPTION
**Pull request by glommer**
Developers using environments like cloudflare or other edge function providers cannot use the filesystem easily for local testing. And the ones with a file system usually don't necessarily know about the file: path.

We have been toying with the idea of spawning a local sqld server, but it has some disadvantages, mainly it is a big (30MB) Rust binary that needs to be downloaded separately.

We don't need any of the replication bits from sqld, so it may be easier to just spawn a webserver and use a local libsql or sqlite file and proxy the requests.

We'd have to have a hrana-server implementation in go, but that doesn't sound too hard.

A bit harder, is making sure that all the responses and error messages are the same as sqld would generate, and keeping that in sync.

This PR adds a very basic wrapper that shows how the devex could be. I didn't worry about returning any valid responses yet, just execute a statement, print it, and done. A first step!

### CODE REVIEW

**Comment by psarna** [comment]
Btw, local-tunnel was recently dropped due to its dependency on libssl, but it was earlier introduced exactly for the purpose of testing with cloudflare: https://github.com/libsql/sqld/pull/340 . Maybe we can do something around that, run a local slim sqld and tunnel it so that it has a public ip address available from cloudflare environment

**Comment by haaawk** [comment]
LGTM

**Comment by glommer** [comment]
how come it looks good to you? It doesn't even work =)

**Comment by glommer** [comment]
@psarna the direction this patch goes is exactly not to use sqld, but have a small local server with a local file

**Comment by glommer** [comment]
moving that out of my fork

**Pull request closed without merging**
