### PR TITLE
Remove password from instance creation request

### PR DESCRIPTION
**Pull request by athoscouto**

### CODE REVIEW

**Comment by haaawk** [comment]
I don't understand this change. Won't it lead to replicas and primary having different passwords?

**Comment by haaawk** [comment]
Also isn't [this](https://github.com/chiselstrike/turso-cli/pull/391/files#diff-ddf0f1c434b9a822221abc406e7ed9304cb352d372d441d75e25da6dd787302aL65-L70) a breaking change for old databases?

**Comment by athoscouto** [comment]
> Won't it lead to replicas and primary having different passwords?

No, that won't happen. Everything is handled on the server side now.

> Also isn't [this](https://github.com/chiselstrike/turso-cli/pull/391/files#diff-ddf0f1c434b9a822221abc406e7ed9304cb352d372d441d75e25da6dd787302aL65-L70) a breaking change for old databases?

Why would it be a breaking change?

**Comment by haaawk** [comment]
> Why would it be a breaking change?

Ok. If we're handling the password on the server side then it's all good. I wish the PR had mentioned that password handling is moved to server side.

**Pull request merged**
